repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        files: (\.bash|\.sh|bashrc|bash_profile|bash_logout)$
        args: [--severity=warning, --external-sources]

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.1.0
    hooks:
      - id: stylua
        args: [--config-path, nvim/.config/nvim/stylua.toml]
