vim.opt.termguicolors=true
vim.opt.backup=false
vim.opt.expandtab=true
vim.opt.hidden=true
vim.opt.hlsearch=false
vim.opt.laststatus=1
vim.opt.number=true
vim.opt.relativenumber=true
vim.opt.shiftwidth=2
vim.opt.softtabstop=2
vim.opt.tabstop=2
vim.opt.splitbelow=true
vim.opt.splitright=true
vim.opt.swapfile=false
vim.opt.undofile=true
vim.opt.wrap=false
vim.opt.smartindent=true
vim.opt.autoindent=true
vim.opt.scrolloff=8

vim.g.mapleader=' '
