vim.opt.background='dark'
vim.opt.termguicolors=true
vim.g.gruvbox_material_palette='original'
vim.g.gruvbox_material_background='medium'
vim.g.gruvbox_material_transparent_background=1

vim.opt.autochdir=true
vim.opt.backspace='indent,eol,start'
vim.opt.expandtab=true
vim.opt.hidden=true
vim.opt.laststatus=1
vim.opt.mousemodel='popup'
vim.opt.backup=false
vim.opt.hlsearch=false
vim.opt.swapfile=false
vim.opt.wrap=false
vim.opt.nu=true
vim.opt.relativenumber=true
vim.opt.shiftwidth=2
vim.opt.softtabstop=2
vim.opt.splitbelow=true
vim.opt.splitright=true
vim.opt.tabstop=2
vim.opt.undodir= os.getenv("HOME") .. "/.vim/undodir"
vim.opt.undofile=true
vim.opt.updatetime=300
vim.opt.updatetime=50
vim.opt.wildignore='*/tmp/*,*.so,*.swp,*.zip,*/node_modules/*'
vim.opt.wildmenu=true

vim.g.mapleader=' '
vim.g.gitgutter_map_keys=0
vim.g.netrw_banner=0
vim.g.netrw_gh=0
vim.g.netrw_hide=1
