# sensible defaults
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*256col*:Tc"
set -g history-limit 10000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -sg escape-time 0
set -g mouse on
set -g focus-events on

set -g extended-keys on
set -g extended-keys-format csi-u
