# ~/.bash_aliases

# Git
alias g='git'
alias gs='git status -sb'
alias gp='git push'
alias gl='git log --oneline --graph --decorate --all'

# Misc utilities
alias ..='cd ..'
alias cls='clear'
alias dnuke='docker system prune -f'
alias k='kubectl'
alias la='ls -a'
alias ll='ls -l'
alias n='$EDITOR ~/ntb/$(date +%y%m%d)-scratch.md'
alias r='source ~/.bashrc'
alias t='task'
alias ta='task add'
alias tm='task modify'
alias td='task done'
alias tx='task delete'
alias tn='task next'
alias tl='task list'
alias ti='task add +inbox'
alias ts='task sync'
alias te='task edit'
alias tc='task context'
alias tf='terraform'
alias v='$EDITOR'
alias week='date +%V'
