remember_window_size no
initial_window_width  1280
initial_window_height 800

map f11 toggle_fullscreen

cursor_shape block
shell_integration no-cursor

map ctrl+shift+enter launch --cwd=current
map ctrl+shift+t launch --cwd=current --type=tab
map ctrl+shift+' launch --cwd=current --location=hsplit
map ctrl+shift+\ launch --cwd=current --location=vsplit

map alt+h neighboring_window left
map alt+j neighboring_window down
map alt+k neighboring_window up
map alt+l neighboring_window right

# retrobox colorscheme
background #1c1c1c
foreground #ebdbb2
cursor #fbf1c7
cursor_text_color #1c1c1c
selection_background #504945
selection_foreground #ebdbb2

color0  #1c1c1c
color1  #cc241d
color2  #98971a
color3  #d79921
color4  #458588
color5  #b16286
color6  #689d6a
color7  #a89984
color8  #928374
color9  #fb5944
color10 #b8bb26
color11 #fabd2f
color12 #83a598
color13 #d3869b
color14 #8ec07c
color15 #ebdbb2
